### ISSUE TITLE
Logo is visibly slow to load

### ISSUE THREAD

**Issue by Bjwebb** [NRGI/resourceprojects.org-frontend#105]
I think there are two reasons for this:
1) the image is a large jpeg. This can be solved by resizing it.
2) the headers are inappropriate for caching. I think this is because it's being served via PHP, rather than directly by apache. This should be fixable by changing the apache config / htaccess to serve it directly.

**Comment by Bjwebb** [comment]
@caprenter has implemented 1). Leaving this issue open to look into 2) in future.

**Comment by caprenter** [comment]
Closing this as 1) is complete and 2) is in a separate issue https://github.com/NRGI/resourceprojects.org-frontend/issues/261 now
