### ISSUE TITLE
Add entry counts

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/resourceprojects.org-frontend#111]
put a simple count in about page:
"A browse interface onto existing project-level reports loaded to the platform" .... currently containing  X payments across Y projects in Z countries made by Q companies,

This will be probably grow in importance as load takes up.

**Comment by anderspeders** [comment]
To elaborate further. 

Could we run a static summary for Monday on the following? 
- Number of projects
- Number of companies and groups
