### ISSUE TITLE
Source service

### ISSUE THREAD

**Issue by timgdavies** [NRGI/resourceprojects.org-frontend#114]
I had issues with queries for /source/ service and Source class clashing, so moved source to sources/

/sources/ is slightly different from other listings, as it takes a URI and then returns the source for that URI, rather than just covering listings. 

However, the split [I've made here](https://github.com/NRGI/resourceprojects.org-frontend/pull/113) may not be appropriate over long-term, and is to be reviewed.

**Comment by Bjwebb** [comment]
As discussed on IRC, we think the best approach is to have a `/source/` service which is a list of Source classes, and to have a differently named service, e.g. `/list-sources/` which takes a URI and then lists the sources.
