### ISSUE TITLE
Correction payment view

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourceprojects.org-frontend#117]
![correcting payment view](https://cloud.githubusercontent.com/assets/1101585/8875965/942aef3a-31ea-11e5-846c-083dadd4ece3.JPG)

Changes: 
1) *Payment to* to *Payment by*
2) Move *Payment to* to the left

**Comment by caprenter** [comment]
There are a number of payment views:
Group page, e.g. http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/company/82e5fad40c9b4640.html
Project page, (as reported) e.g.  http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/project/tt/cebl-1gmjgu.html
Company Page, e.g. http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/company/82e5fad40c9b4640.html
Companypayment page, e.g. http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/companypayment/tt/b3cba34efa8097f5.html
Country page e.g. http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/country/tt.html


And also a GovernmentRecipt page that I realise needs creating

I will check all of the above.
Once I commit a change, I'll let you know when the site has updated and then @anderspeders should be able to check

**Comment by anderspeders** [comment]
Yes, to this is tricky. 

Note that the examples above @caprenter should not all have the column header changed: 

1) Should not be changed, but should remain **Paid to** [country government]
Group page, e.g. http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/company/82e5fad40c9b4640.html

Company Page, e.g. http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/company/82e5fad40c9b4640.html

2) Column header be changed from **Paid to** --> **Paid by** and moved to left column
Project page, (as reported) e.g. http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/project/tt/cebl-1gmjgu.html

**Comment by caprenter** [comment]
We got this covered in https://github.com/NRGI/resourceprojects.org-frontend/commit/36c3542eb1ab3f5f5fb999433d6a9f21c0e42457
