### ISSUE TITLE
No Results

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#126]
When there are no Production Stats, or no payments:
e.g. http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/project/id/bu-q4z9j8.html
http://alpha.resourceprojects.org/company/fe34220874ae57a4.html

Then we should be able to detect this.

We should show a message instead of the table - so keep the heading but add the text - "No results found" or something

**Comment by Bjwebb** [comment]
@caprenter Sorry, didn't get chance to look at this this morning. Won't try doing this on the train, as I don't want to risk breaking other stuff.

**Comment by Bjwebb** [comment]
@caprenter Just to double check, is this still useful for me to look into?

**Comment by caprenter** [comment]
yes I think so

**Comment by caprenter** [comment]
Note:
Production table should read left to right
Year, volume, unit, price, price per unit id

I plan to implement this

**Comment by davidmihalyi** [comment]
Realized the table is missing commodity: Please use following @caprenter 
From left to right:
#project+production+year	#project+production+volume	#project+production+unit	#project+production+commodity	#project+production+price	#project+production+priceUnit   (displaying notes unclear, this is probably for later)

**Comment by Bjwebb** [comment]
@caprenter For dealing with no results, use something like `{% if models.payments|length %}
`

Not sure if the most recent two comments belong on this issue?

**Comment by caprenter** [comment]
You're right those comments above could do with moving.
However I have a commit that address both problems coming along, so keeping this here for now...
