### ISSUE TITLE
Ensure no double counting

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourceprojects.org-frontend#130]
![statoil duplicates](https://cloud.githubusercontent.com/assets/1101585/8901006/3784109c-3413-11e5-8c67-8530cf1e712d.JPG)

Statoil seems for some reason have been loaded twice resulting in duplicates.

For some data points it seems as if they are reported twice, each with a unique payment id: 
![staoil2](https://cloud.githubusercontent.com/assets/1101585/8901046/8be9b16e-3413-11e5-885e-ab560886b794.JPG)
 
Is there a link to data so that we can maybe do a manual clean up?

**Comment by timgdavies** [comment]
I've fixed the country name duplication manually for the moment, but we
will need to introduce some data validation processes when data is loaded
to deal with this kind of thing in a more stable environment.

I believe the payment duplication is down to the incoming data having lines
for 'totals' as well as specific payment types. Again, we need to think
about whether we want to handle this at the day or presentation layer.

On Mon, Jul 27, 2015 at 8:57 AM, Anders <notifications@github.com> wrote:

> [image: statoil duplicates]
> <https://cloud.githubusercontent.com/assets/1101585/8901006/3784109c-3413-11e5-8c67-8530cf1e712d.JPG>
>
> Statoil seems for some reason have been loaded twice resulting in
> duplicates.
>
> For some data points it seems as if they are reported twice, each with a
> unique payment id:
> [image: staoil2]
> <https://cloud.githubusercontent.com/assets/1101585/8901046/8be9b16e-3413-11e5-885e-ab560886b794.JPG>
>
> Is there a link to data so that we can maybe do a manual clean up?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourceprojects.org-frontend/issues/130>.
>



-- 


+44 (0)7834 856 303
@timdavies
http://www.timdavies.org.uk

**Comment by timgdavies** [comment]
There are now links to source data, and I've been loading data and synchronising carefully to avoid double counting. Hopefully this will resolve the outstanding issues.
