### ISSUE TITLE
Create service to display details of the ontology

### ISSUE THREAD

**Issue by timgdavies** [NRGI/resourceprojects.org-frontend#131]
To help users understand the ontology (and to help sanity checking the ontology), I've started work on a service to sit a /ontology/ (for now, could go to /def/) which will output documentation of the ontology.

This is on the [ontology viewer](https://github.com/NRGI/resourceprojects.org-frontend/tree/ontology-viewer) branch, and is current work in progress.

**Comment by Bjwebb** [comment]
@timgdavies What's the status of this?

I've deployed a copy of this to http://ontology.lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/ontology now that we've got RDF support in the ETL layer, and I've loaded the ontology http://etl.nrgi-dev2.default.opendataservices.uk0.bigv.io/dataload/12/

**Comment by timgdavies** [comment]
You could merge the ontology branch in but it's not really ready for public
consumption yet so let's leave as post-beta
