### ISSUE TITLE
Country Location Data

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#137]
We need a way to centre our maps for a country page. E.g for Algeria the map centre should be 28,3 (lat,lng). I found that by googling. 

@timgdavies @Bjwebb Do we need to create our own dataset of these values and add that data to the datastore?

I'm not sure how to load it into lodspeakr templates otherwise

**Comment by timgdavies** [comment]
I should be able to get a dataset of this loaded to the datastore at the
end of this week.

I'm not sure, but there might also be libraries that can take the ISO code
and do this as well...

On Wednesday, September 30, 2015, caprenter <notifications@github.com>
wrote:

> We need a way to centre our maps for a country page. E.g for Algeria the
> map centre should be 28,3 (lat,lng). I found that by googling.
>
> @timgdavies <https://github.com/timgdavies> @Bjwebb
> <https://github.com/Bjwebb> Do we need to create our own dataset of these
> values and add that data to the datastore?
>
> I'm not sure how to load it into lodspeakr templates otherwise
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourceprojects.org-frontend/issues/137>.
>


-- 


+44 (0)7834 856 303
@timdavies
http://www.timdavies.org.uk

**Comment by caprenter** [comment]
..and default zoom level...

**Comment by timgdavies** [comment]
In [this spreadsheet](https://docs.google.com/spreadsheets/d/1JeQbeXQacUJWNR2nPesGDQb9BJGHhVvri_Nk8zxj1Mg/edit#gid=729500090) I've taken a public domain list of country centroids, and a GNU Licensed set of bounding boxes for countries, and marked them up for import.

This should ensure all countries have a lat, long pair, and a set of additional properties in the ```misc/```  namespace (I've not added these to ontology yet) for their bounding boxes. 

To ensure this is robust, we need to either:

(a) Find a more comprehensive list of bounding boxes;

(b) Make sure queries and widgets are forgiving when bounding boxes are absent

Or, ideally, both.

**Comment by caprenter** [comment]
This is all in place now - thanks!

**Comment by caprenter** [comment]
..ah sorry - everything is in place for what we need for this milestone, so pushing the remaining issues to post beta and re-opening

**Comment by timgdavies** [comment]
Closing as we've not found a need for bounding boxes at this stage.
