### ISSUE TITLE
Participanting Companies

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#141]
Typo - can you spot it!

http://alpha.resourceprojects.org/project/dz/hamo-xaqalm.html

**Comment by davidmihalyi** [comment]
Haha, company pants

David Mihalyi | Economic Analyst
Natural Resource Governance Institute
(formerly the Revenue Watch Institute – Natural Resource Charter)
1 Knightrider Court, London EC4V 5BJ, UK  |
Office: +44 20 7332 6118 | Mob: +44 (0) 77 9858 6290
dmihalyi@resourcegovernance.org<mailto:dmihalyi@resourcegovernance.org> | www.resourcegovernance.org | Skype: davidmihalyi

**Comment by caprenter** [comment]
Closing this as in the newer version we simply have a 'Companies' table - we drop the (partici)pants completely! (I couldn't resist!)
