### ISSUE TITLE
Add glossary

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/resourceprojects.org-frontend#157]
Hi @caprenter and @timgdavies 

Glossary is completed and peer-reviewed.

Can you add a glossary to main page:
![image](https://cloud.githubusercontent.com/assets/13120783/10576575/30741924-765c-11e5-98a9-73e6e9f1d629.png)

And the text is here:
https://docs.google.com/document/d/1dp1ETInmfx6dSMnfycYI_nTAZ0by4F0Ycu0qgoSnMDs/edit

Please disregard comments.
Do not add the FAQ section at bottom of page, which is still under construction.

**Comment by timgdavies** [comment]
I'll take a look at this this evening @caprenter - as it may be possible to auto-generate this from loading the ontology. Will let you know later.

**Comment by caprenter** [comment]
I think this has been implemented.

I copied the document into a static page:
http://lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/glossary.html

**Comment by timgdavies** [comment]
Agreed. I've looked into auto-generation of ontology - but this looks like it won't quite cover what the glossary page needs to do - so leaving to the future.
