### ISSUE TITLE
Country page design

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#16]
Wireframes for country pages should be agreed with @anderspeders 
Wireframes for country projects should include payments data
Wireframe pages should be implemented

**Comment by timgdavies** [comment]
We need to capture Years of payments

**Comment by anderspeders** [comment]
Example of user story: PWYP Indonesia would like to see a page with information on project payments in Indonesia. 

The page should also allow for the availability of including a map with the geo-referenced data.

**Comment by caprenter** [comment]
So, for example:
http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/country/id.html
does have a table of payments data.

We don't yet have country maps, as we don't yet have a reliable source of geographic data to use for this.

**Comment by caprenter** [comment]
![3rp_1024](https://cloud.githubusercontent.com/assets/185467/8525499/19f75cc0-23f9-11e5-8d62-29b2f6cf2949.png)

**Comment by timgdavies** [comment]
Beta wireframe: 

![uploads/902cdfe1-0a72-4ac8-94b2-286e55670d46/country.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F902cdfe1-0a72-4ac8-94b2-286e55670d46%2Fcountry.png)

**Comment by caprenter** [comment]
See also #153

**Comment by caprenter** [comment]
We have something in place for Mexico
