### ISSUE TITLE
 global project map

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/resourceprojects.org-frontend#165]
global project map with markers (if this is limited work when time allows). this is a great visual UI in full screen mode. I think it would be a real crowd-pleaser...

**Comment by caprenter** [comment]
Map temporarily at:
http://feature-projects-map.lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/

See discussion at:
https://github.com/NRGI/resourceprojects.org-frontend/pull/177

**Comment by caprenter** [comment]
We now have this at http://alpha.resourceprojects.org/map

We have this as an alternative to the map on the projects list as we're still concerned that loading this every time that page loads (and when lots of people are using it) is not going to help the server.

We do however need to link to this page from somewhere..

@davidmihalyi Can we discuss

**Comment by davidmihalyi** [comment]
Ok, that sounds like a practical solution. We can figure a useful place to add a link on project page to view all projects on map?

Sent from mobile;  pls excuse brevity and typos.

On 22 Oct 2015, at 21:13, caprenter <notifications@github.com<mailto:notifications@github.com>> wrote:


We now have this at http://alpha.resourceprojects.org/map

We have this as an alternative to the map on the projects list as we're still concerned that loading this every time that page loads (and when lots of people are using it) is not going to help the server.

We do however need to link to this page from somewhere..

@davidmihalyi<https://github.com/davidmihalyi> Can we discuss

-

**Comment by caprenter** [comment]
Done
