### ISSUE TITLE
Project page design

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#17]
Wireframes for project pages should be agreed with @anderspeders 
Wireframe pages should be implemented

**Comment by caprenter** [comment]
I don't think we're able to link licences to projects at the moment @timdavies - is that correct.

If so we can remove the license table from project pages. 

@timdavies if this is correct can you assign this to me?

**Comment by caprenter** [comment]
https://slack-files.com/files-tmb/T0312GL2V-F072Z6J4R-aff1dab92d/6rp_1024.png

**Comment by timgdavies** [comment]
Beta wireframe: 

![uploads/b4cf8fb7-db24-47ad-b8da-0f393b023005/project.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb4cf8fb7-db24-47ad-b8da-0f393b023005%2Fproject.png)

**Comment by caprenter** [comment]
We have something in place for Mexico. We may want to revisit this ticket going forward, but closing for now
