### ISSUE TITLE
Company pages design

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#18]
Wireframes for company pages should be agreed with @anderspeders 
Wireframe pages should be implemented

**Comment by timgdavies** [comment]
From check-in call: **Corporate ownership information and company groupings information is very valued**

**Comment by timgdavies** [comment]
Our current model allows stake-holding in companies in which there can be:

* A person with a stake in a company
* A company with a stake in a company

So - for any company, we could look up all those companies who have a stake in it.

But, **corporate groupings** could be a slightly different matter? (See OpenCorporates notion of a Corporate Grouping).

**Comment by anderspeders** [comment]
So as an example: 

As a user I would like to view and navigate the site based on corporate groups - for example *ConocoPhilillips*.

As an advianced user I would like to be able to navigate *all companies within the ConocoPhillips group*: 
ConocoPhillips (Grissik) Ltd.
ConocoPhillips (South Jambi) Ltd.
ConocoPhillips Amborip VI LTD
ConocoPhillips Arafura Sea Block Indonesia LTD
ConocoPhillips Grissik LTD
ConocoPhillips Indonesia INC
ConocoPhillips Indonesia Inc. Ltd.
ConocoPhillips Kuma LTD
ConocoPhillips South Jambi LTD
ConocoPhillips Warim LTD

**Comment by anderspeders** [comment]
I would suggest - a company group view and a company full list view.

**Comment by caprenter** [comment]
Payment types, and dates 
Simple Bar chart e.g what did Tullow pay in 2013, 14

**Comment by caprenter** [comment]
![uploads/bec535ad-df91-4b6c-8ab6-5aad0d5068e5/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbec535ad-df91-4b6c-8ab6-5aad0d5068e5%2Fblob)

**Comment by anderspeders** [comment]
Thanks for updating this ticket.

**Comment by timgdavies** [comment]
Beta wireframe: 


![uploads/46f590a4-5d7e-44a3-bf74-f1c2727019eb/company_list.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F46f590a4-5d7e-44a3-bf74-f1c2727019eb%2Fcompany_list.png)

**Comment by caprenter** [comment]
This is under control, but just moving into the Beta milestone

**Comment by caprenter** [comment]
We've got an agreed page in place for Mexico.

Filters are the main thing missing, but the data does not necessarily support them uniformly across the site, so they were dropped.
Some of the infrastructure is still in place tho.
