### ISSUE TITLE
Display commodity on project info

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/resourceprojects.org-frontend#181]
Project info currently only displaying #commodity+commodityType    but not #commodity  (ie. mining and not Copper).

**Comment by caprenter** [comment]
Addressed in https://github.com/NRGI/resourceprojects.org-frontend/pull/180

**Comment by caprenter** [comment]
This has been merged and should be working. 

We also have work on reducing duplicates here: https://github.com/NRGI/resourceprojects.org-frontend/pull/202

so closing this ticket
