### ISSUE TITLE
Company page needs additional info

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/resourceprojects.org-frontend#184]
For the company page: 
Add a short list with:
#company+openCorporatesURL (open in new tab) 
#company+website (open in new tab) 
and company+country

**Comment by caprenter** [comment]
This is already queued for inclusion:
https://github.com/NRGI/resourceprojects.org-frontend/pull/172

**Comment by caprenter** [comment]
..although I'm not entirely clear from the data whether or not we are generating company+country in the triples @timgdavies ?

**Comment by timgdavies** [comment]
It looks like the ontology is currently missing the company+country relationship. Just testing an updated version now....

**Comment by timgdavies** [comment]
I've just pushed an updated ontology to https://github.com/NRGI/resource-projects-etl/commit/f3b2f723334753be266dbcb40a5bee69e0153937 which should have this linkage in...

but fear I may have changed more than I intended (@bjwebb can you check)

**Comment by Bjwebb** [comment]
Looks okay to me, apart from a rather messy merge commit that I've removed. Rebased commit at https://github.com/NRGI/resource-projects-etl/commit/bfaf7a5ce1e05447f5bf8e813ee403ab776ec796. Probably don't push directly to master on the etl branch in future.

**Comment by caprenter** [comment]
This is done
