### ISSUE TITLE
Are all Angola project payments the same?

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#186]
You won't see this on the live set up yet because of:
https://github.com/NRGI/resourceprojects.org-frontend/pull/173

but I think the payments data on Angola projects is the same on every project

**Comment by timgdavies** [comment]
Looking at the [Angola input data](https://docs.google.com/spreadsheets/d/1j9IDzCxCd2a70viGa8UejqWfxJDrUS87u7ROl8p8Hgc/edit#gid=204566568) I only see ```GovernmentReceipt``` - but I don't see any payments from that file.

**Comment by caprenter** [comment]
I've recently altered the payments data to show government receipts (if available), as well as payments.

(Angolan)  - seem to clearly have these receipts 'attached' to projects, so it seems they should be shown.

So one issue is - should we be sowing this and if so where?

The other issue is that in Angolan data, all projects seem to have the same government receipts attached.

**Comment by caprenter** [comment]
This has been merged
