### ISSUE TITLE
Country code within project identifiers is inconsistent in the data

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#187]
Specifically, the case of the country ID is both Upper and lower inconsistently.

This will not break anything as such, but could be fixed in a later iteration

**Comment by timgdavies** [comment]
Yep. This can be fixed in TagLifter.

We might want to do this just after Mexico demos in order to have stable URIs once the beta is out there.

**Comment by caprenter** [comment]
@timgdavies I think we move this to the Post-Beta milestone?

**Comment by timgdavies** [comment]
Agreed. This is post beta.

**Comment by davidmihalyi** [comment]
Sure! Would be great to talk through naming convention and id generating in Mexico

Sent from mobile;  pls excuse brevity and typos.

On 22 Oct 2015, at 23:41, timgdavies <notifications@github.com<mailto:notifications@github.com>> wrote:

Agreed. This is post beta.
On 22 Oct 2015 4:07 pm, "caprenter" <notifications@github.com<mailto:notifications@github.com>> wrote:

> @timgdavies <https://github.com/timgdavies> I think we move this to the
> Post-Beta milestone?
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourceprojects.org-frontend/issues/187#issuecomment-150341620>
> .
>

-

**Comment by timgdavies** [comment]
It should all now be uppercase. 

Changes have been made to the templates and TagLifter to address this.
