### ISSUE TITLE
Displaying Preferred and Alternative labels for a project

### ISSUE THREAD

**Issue by timgdavies** [NRGI/resourceprojects.org-frontend#19]
We set language typed ```skos:prefLabel``` values when converting data and we first discover a name for an organisation.

We can also set ```skos:altLabel``` values. 

It is currently possible that multiple ```skos:prefLabel```s for a given entity, **but** we should look to make it an administration task in these cases to convert different ```prefLabel``` into ```altLabel```, leaving only one preferred prefLabel.

For the **interface** we should explore the best way to expose the altLabel, for example, through a longer list that appears when you hover over a project name. 

This needs to be factored into the wireframes for #17

**Comment by anderspeders** [comment]
Looks good, 

From a user point of view I would imagine this could appear on the project page as: 

"<prefLabel> South Natuna Sea B
This is also known as <altLabel> **South Natuna** according to <altSource>"

We should also add a disclaimer or FAQ: "Why are multiple names listed for the same project?"

**Comment by timgdavies** [comment]
The new data load template includes an alias field, allowing project names to be aliased - and controls better to avoid multiple project names being created. 

We should ensure queries are robust for this. 

Assigning Anders to suggest a response to the FAQ question:

"Why are multiple names listed for the same project?" 

as I suspect there is a more resource governance specific answer to this than "We had multiple names in the input data..."

**Comment by caprenter** [comment]
I have alternative labels showing on a Project page - leaving this here and open because it may need implementing elsewhere
