### ISSUE TITLE
Commodites not linked to production stats

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#196]
In the model we're not linking commodities with productions stats.

The data is in tab8 of the spreadsheet
#project+production+commodity

See:
http://lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/default-view/http/resourceprojects.org/project/PE/anta-nf2afx

and then e.g.
http://lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/production/PE/19b432b3baa4a12e.html

**Comment by timgdavies** [comment]
Ok - yes - missing link in the model again. Just adding and testing now...

(starting to think I must have lost some changes at some point... definitely need to add some ontology tests post-Mexico)
