### ISSUE TITLE
payment type tax has 2 names

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#197]
See:

http://lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/paymenttype/eurd/tax.html

I think I can filter this out in the query using:
FILTER (str(?type_name) != "Taxes levied on the income, production or profits of companies,")

**Comment by timgdavies** [comment]
That will work for now - yes. I'll look into which source template that is coming from - and will look into whether the templates should be updated to only pass through a code, and not a name for the category to avoid this coming up in future.

**Comment by caprenter** [comment]
Done

**Comment by timgdavies** [comment]
Tracked down in source data and removed.
