### ISSUE TITLE
Provide lookup of provenance information

### ISSUE THREAD

**Issue by timgdavies** [NRGI/resourceprojects.org-frontend#20]
## Background

For most URIs in our dataset, it should be possible to run a query to find out which datasets it was derived from. We set ```prov:wasDerivedFrom``` properties at the entity level, pointing to the dataset row it came from, and pointing from the dataset row to the source dataset. 

```ttl
<http://www.resourceprojects.org/companypayment/id/55895f579368d23a> a base:CompanyPayment ;
    base:currency "USD" ;
    base:date "2009-01-01T00:00:00"^^xsd:dateTime ;
    base:payee <http://www.resourceprojects.org/country/id> ;
    base:payer <http://www.resourceprojects.org/company/id/55895f53000630e0> ;
    base:relatedProject <http://www.resourceprojects.org/project/id/se-rjz70i> ;
    base:value 6,175,000";
    prov:wasDerivedFrom <http://www.resourceprojects.org/prov/source/55895de27e6f4cf3/row/39> .

<http://www.resourceprojects.org/prov/source/55895de27e6f4cf3/row/39> a base:SourceRecord ;
    prov:wasDerivedFrom <http://www.resourceprojects.org/prov/source/55895de27e6f4cf3> .

<http://www.resourceprojects.org/prov/source/55895de27e6f4cf3> a prov:Entity ;
    base:Converted "2015-06-01" ;
    base:Source_Type "official" ;
    base:author "Tim Davies" . # Example properties only. 
```

With the [provenance ontology](http://www.w3.org/TR/prov-o/#wasDerivedFrom) loaded into our datastore, and reasoning enabled, the ```prov:wasDerivedFrom``` property should be transitive, allowing a query which looks for:

```sparql
  <uri> prov:wasDerivedFrom ?x.
```

to find both the row, and the dataset, in which a particular entity has been discovered. Datasets *should* be marked up with some meta-data about the source, and the point of importing that data. 

## Proposal

We should provide a LODSPeakr page which retrieves the provenance information for any given URI it is handed. 

We should add a mouse-over link for any URI in the data, which links to that provenance information (this might be possible to do by adding RDFa or data attribute markup to entities on the page, and then using jQuery etc. to manage those pop-ups). 

> Note: It is possible for an entity to have properties derived from multiple datasets, so this method does not 100% show where every fact came from: to do that we may need to segment data into different graphs...

**Comment by Bjwebb** [comment]
Might a URI have information about it from multiple sources? If multiple sources, is it important/useful to also know for an individual triple what the specific source was?

**Comment by timgdavies** [comment]
Without either [reification](http://patterns.dataincubator.org/book/reified-statement.html), using quads, or managing named graphs carefully, it is tricky to track the provenance of each individual triple within the linked data - although the information we're talking about tracking here should let people go back quite a way towards the source to verify where data came from.

In future I think we might want to explore use of named graphs, particularly to annotate graphs that contain 'verified' data and those that do not... but I'm not sure this is something for the current sprints...

**Comment by timgdavies** [comment]
For most records we should soon have both ```prov:wasDerivedFrom``` information, and a ```source``` relationship pointing to a ```Source``` entity which has more narrative content about the source. 

It would be good to have:

(a) A nice list of ```Source``` entities;
(b) An easy way to move from an entry in the platform to its ```source```

**Comment by caprenter** [comment]
I think for example that this is a source record, but I don't see anything useful to latch onto - i.e. a name of the document it came from

**Comment by timgdavies** [comment]
There are now two kinds of source present

/prov/source/ which are automated provenance information, and /source/ records, which are more manually curated.

An example of the second would be:

http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/source/Zambia2010.html

**Comment by caprenter** [comment]
This work is now being done in the beta milestone. I think most of it is covered, but will bump this to beta

**Comment by caprenter** [comment]
I'm going to push this to post-beta
I think it can actually be closed as work is done elsewhere, but keeping open just in case

**Comment by timgdavies** [comment]
The source links on each page now handle this.
