### ISSUE TITLE
Check consisentency of size of maps at top of pages

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#220]
I think just the country view page is 480px

everything else is 240px

If we don't have the filters (or even if we do now, they are small) - maybe the country page map should also be 240px high

**Comment by davidmihalyi** [comment]
Fine to keep as is, with larger country map.

**Comment by caprenter** [comment]
ok - thanks.

**Comment by caprenter** [comment]
Checked and consistency looks good
