### ISSUE TITLE
list-sources page doesn't work

### ISSUE THREAD

**Issue by Bjwebb** [NRGI/resourceprojects.org-frontend#228]
e.g. http://lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/list-sources/http/resourceprojects.org/country/PE

Originally reported at https://github.com/NRGI/resourceprojects.org-frontend/pull/171#issuecomment-149840355

**Comment by caprenter** [comment]
I'll take a quick look at this if you like - will look after lunch and let you know if I'm on top of it

**Comment by timgdavies** [comment]
Thanks - I'm not going to have chance to look before late today - but this would be really useful to have for tomorrow if possible.

**Comment by caprenter** [comment]
I've taken a look and I'm stumped - I don't even know where to start sorry!

**Comment by timgdavies** [comment]
Addressed in pull request https://github.com/NRGI/resourceprojects.org-frontend/pull/255
