### ISSUE TITLE
Dates in sources view

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#232]
Some zero dates and some 1970-01-01

**Comment by caprenter** [comment]
This was seen as low priority.

It is a bug and it does need fixing, but we can live with it.

**Comment by timgdavies** [comment]
This is a data source error - rather than interface error. 

In future we may want to add this to validation checks that the staging server would help with (e.g. custom queries to look for common data quality errors).

**Comment by timgdavies** [comment]
I've got a fix in #260 but no dev environment. Would you be able to merge and test?

**Comment by caprenter** [comment]
The pull request should deal with the 1970-01-01 dates for when blank/empty dates are supplied.

However, there are still data quality issues with dates that may be passed to the filter that prints the dates out, which may lead to 1970... being sent to the screen.

There are also some non-sense dates in the data

**Comment by timgdavies** [comment]
That's ok. As long as we know any remaining errors will be from dodgy data
at source we can go back and fix at source. I'll look at whether more
validation can be added to the spreadsheet template.
