### ISSUE TITLE
Timeout on alpha.resourceprojects.org Mexico page

### ISSUE THREAD

**Issue by Bjwebb** [NRGI/resourceprojects.org-frontend#235]
http://alpha.resourceprojects.org/country/MX.html

```
Fatal error: Maximum execution time of 30 seconds exceeded in /var/www/html/lodspeakr/classes/Utils.php on line 26
```

This is odd because http://lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/country/MX.html takes longer than 30 seconds, but doesn't produce the same error. I also can't reproduce the error.

**Comment by davidmihalyi** [comment]
This is a very high priority bug to fix, hope you can find a way around it!


David Mihalyi | Economic Analyst
Natural Resource Governance Institute
(formerly the Revenue Watch Institute – Natural Resource Charter)
1 Knightrider Court, London EC4V 5BJ, UK  |
Office: +44 20 7332 6118 | Mob: +44 (0) 77 9858 6290
dmihalyi@resourcegovernance.org<mailto:dmihalyi@resourcegovernance.org> | www.resourcegovernance.org | Skype: davidmihalyi

**Comment by Bjwebb** [comment]
Discovered one of the problems here - we've been using the pattern of an if statement within a for loop to pick out the correct value of an array (which is a bit ugly, but the nicest way we've found so far given the constraints of lodspeakr). However, if you're not careful, this generates a lot of whitespace, in the case of the mexico page over 50MB!

**Comment by Bjwebb** [comment]
Reducing the whistespace in the page means we no longer get a timeout. Therefore, I'm closing this issue.

Note that if data increases considerably we may hit the 30 seconds limit again, but I don't think it's worth upping it pre-emptively because our page loads shouldn't take that long - and if they do timing out may be the preferable option so that people can still access other pages on the site.
