### ISSUE TITLE
sameas filters removed, is this a problem at all?

### ISSUE THREAD

**Issue by Bjwebb** [NRGI/resourceprojects.org-frontend#240]
https://github.com/NRGI/resourceprojects.org-frontend/pull/239/files?diff=unified#diff-ee3106f224c7bb9336f5e162919fd7feL16

I think this is fine for now, as I don't think we have sameas in our data at the moment. Is this going to possibly be a problem further along the line?

**Comment by caprenter** [comment]
BTWcI removed those because I was going for  a 'strip everything out that I don't think is doing thing' approach - but I'm not 100% certain of the consequences!

**Comment by timgdavies** [comment]
This is not an issue for now. We've not ended up making any use of sameAs relationships at present.
