### ISSUE TITLE
Project shows no companies, when I think it should

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#253]
Project Animon
http://alpha.resourceprojects.org/project/PE/anim-u4py9y.html

I'm not seeing any 'stakes' in the data here, but there is stakes data in the test fixtures for example

**Comment by caprenter** [comment]
I can confirm that there is no stakes data in the raw data for this project.

The fixture data against which I am comparing is: 
https://github.com/NRGI/resourceprojects.org-frontend/blob/master/fts/fixtures/peru.ttl

**Comment by caprenter** [comment]
@timgdavies I'm not sure why the data used in live is different from the test data - we should probably update one or the other.

**Comment by timgdavies** [comment]
I can only assume the source spreadsheet has changed since the last conversion was run. I can't find any company information for Animon project in the source, so I suggest updating the fixture from the latest version on dev.

**Comment by caprenter** [comment]
On line 61 of tab 8 of this spreadsheet:
https://docs.google.com/spreadsheets/d/1gl3syhKsI-pR_lx3KykuKOLnHrp7ir2fRxjaPTO3DgM/edit#gid=708538582
(is that the right sheet?)
I see the Animon project with an associated company. The company is the one I see in the fixture data.

**Comment by timgdavies** [comment]
Interesting. The project->company linkage is picked up from Sheet 6., so I don't think TagLifter is capturing the relationship from this sheet now. 

This behaviour has updated: as earlier versions were looking for all-and-any possible relationships.

I think in this case the behaviour is ok - and the company-project link should be explicitly declared in Sheet 6 if wanted.

**Comment by caprenter** [comment]
understood - great. thnks
