### ISSUE TITLE
Project page downloads

### ISSUE THREAD

**Issue by timgdavies** [NRGI/resourceprojects.org-frontend#258]
In [this issue](https://github.com/NRGI/resource-projects-dataload/issues/29) @davidmihalyi reported duplicates in the CSV download for production stats at http://alpha.resourceprojects.org/project/PH/apma-ku0f7d.html

On testing I see this duplication, but also see much less data in the download for Payments than is given on the page. 

Check both download and table are using the same queries...

**Comment by caprenter** [comment]
The duplicates should have been handled in this:
https://github.com/NRGI/resourceprojects.org-frontend/pull/252

Will look at the downloads tho.

**Comment by caprenter** [comment]
Sorry - There were duplicates in the productions stats TABLE that was sorted out in #252 

Will now check the downloaded csv on that page for Productions stats and Payments

**Comment by caprenter** [comment]
I've looked into this and think the download is using the query I would expect it to use.

The template does not do anything in particular to filter the data returned from the query - the query should do it all.

Assigning to Ben to investigate.

**Comment by Bjwebb** [comment]
I think this is now fixed in `master` http://lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/project/PH/apma-ku0f7d.html

@caprenter @timgdavies Could you double check that behaves as you'd expect.

**Comment by caprenter** [comment]
Looks ok to me - but the link you supplied does not work. I had to go to:
http://lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/project/PH/apma-l9nepr.html
(is that a problem?)

**Comment by Bjwebb** [comment]
I think that's just an expected consequence of @timgdavies 's data refresh.

**Comment by timgdavies** [comment]
Correct. The IDs will have all changed in the refresh - but have now been synchronised into the incoming data, so should not change into the future.
