### ISSUE TITLE
Company URIs and countries

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#27]
Currently Company URIs contain the country in the path. e.g.
South Madura Exploration Company LTD
http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/Company/id/557a977bfe15c3bc.html

In this set up:
557a977bfe15c3bc, should be enough to be a unique identifier

So is the /id/ in the path (for Indonesia) necessary.

I think I can see a case where a company is working in Indonesia, but is not an Indonesian company for example?

So does this need to change?

**Comment by timgdavies** [comment]
Updated taglifter script removes the country from the default generated company identifiers.
