### ISSUE TITLE
Payment date to payment year - in company view

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourceprojects.org-frontend#36]
![payment date to payment year](https://cloud.githubusercontent.com/assets/1101585/8455437/a24ab3ae-1fd2-11e5-96ac-dfcbee629629.png)

Suggesting this correction.

**Comment by caprenter** [comment]
See: https://github.com/alangrafu/lodspeakr/wiki/Filters-in-LODSPeaKr for implementation of this

**Comment by caprenter** [comment]
Fixed in https://github.com/NRGI/resourceprojects.org-frontend/commit/ed28d5c4290f10229e77cb5f36e9e45fb828a10e

**Comment by caprenter** [comment]
It seems to me as though some data has timestamp dates, and other data just has the year.
The fix above returns '1970' if there is no date field.

**Comment by anderspeders** [comment]
Ok, let's discuss on the call.

**Comment by caprenter** [comment]
Hopefully the above fix will use the date if it is available, otherwise it uses the year. If neither is available it displays nothing.

**Comment by caprenter** [comment]
Closing this, but see also #61

**Comment by caprenter** [comment]
Yes, this was fixed in https://github.com/NRGI/resourceprojects.org-frontend/commit/f4f8f59b72636fd466e60a161e1747cdf5b78412
