### ISSUE TITLE
Friendly 404 / Resource Not Found page

### ISSUE THREAD

**Issue by timgdavies** [NRGI/resourceprojects.org-frontend#38]
At the moment the page view for a resource not being found is a unthemed page saying 'LODSPeaKr couldn't find the resource <resource>'.

It would be good to provide a themed page.

**Comment by Bjwebb** [comment]
https://github.com/alangrafu/lodspeakr/wiki/Status-pages describes how to do this.

**Comment by caprenter** [comment]
We have a 404, and the 500 error is being dealt with in #69
