### ISSUE TITLE
Add sorting features for each column

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourceprojects.org-frontend#44]
As for example done with this site: 
http://itemizer.herokuapp.com/

**Comment by byndcivilization** [comment]
You can just just use the "data-sortable" th option.

**Comment by caprenter** [comment]
This should be straight forward.

**Comment by caprenter** [comment]
There is a proposed fix for this, that involves moving the theme to bootstrap 3. Unfortunately that breaks the 'typeahead' search - which is really useful, so we're still dealing with that.

**Comment by caprenter** [comment]
Sorting is now available. As we finalise the tables we may fiddle with this as we go
