### ISSUE TITLE
Correct amount format

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourceprojects.org-frontend#45]
Currently the amount is not written out in full: 

![amounts - write out full](https://cloud.githubusercontent.com/assets/1101585/8491058/a77d62e2-2101-11e5-994e-46ecba05b51e.png)

**Comment by caprenter** [comment]
This looks to me as though this is how it is in the data. See for example:
http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/default-view/http/resourceprojects.org/companypayment/gh/a705cc6fdcb315f1

@timgdavies can you check?

**Comment by timgdavies** [comment]
Yes - this is a data input issue that we need to deal with.

**Comment by caprenter** [comment]
I think this is done?

**Comment by timgdavies** [comment]
Added this as an ETL issue and able to close this now. 

https://github.com/NRGI/resource-projects-etl/issues/34
