### ISSUE TITLE
List URLs don't match URIs from the data

### ISSUE THREAD

**Issue by Bjwebb** [NRGI/resourceprojects.org-frontend#46]
e.g. we've now got rid of /data/ and use lowercase in data URIs like http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/country/dz.html

.. so, our list URLs like http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/data/Country should be changed to http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/county/

**Comment by caprenter** [comment]
@Bjwebb This is assigned to me - what do I need to do?

**Comment by Bjwebb** [comment]
Rename the services. If it's not clear how to do that, then assign back to me.
