### ISSUE TITLE
Separate namespaces for data and model

### ISSUE THREAD

**Issue by timgdavies** [NRGI/resourceprojects.org-frontend#52]
In the LodSpeakr configuration we currently define:

```php
$conf['ns']['local']   = 'http://resourceprojects.org/';
```

We should consider switching to 

```php
$conf['ns']['rpd']   = 'http://resourceprojects.org/';
$conf['ns']['rp']   = 'http://resourceprojects.org/def/';
```

In order to better manage the distinctions between Resource Projects Data, and the Resource Projects model, and to establish consistent use of namespace prefixes.

**Comment by caprenter** [comment]
I'm unsure of what action I need to take here. Is it just a case of altering the settings file, or is there other stuff to consider? Should @Bjwebb take a look also?

**Comment by anderspeders** [comment]
We can backlog this to post-alpha

**Comment by timgdavies** [comment]
This only requires a change to settings.php
