### ISSUE TITLE
Can we also load Kosmos data?

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/resourceprojects.org-frontend#53]
This would need to be scraped, but only 10 projects in this: 3 in Ghana, 4 in Ireland, 3 in Mauritania.
http://www.kosmosenergy.com/responsibility/transparency.php

**Comment by timgdavies** [comment]
I've created an issue for this in the dataload tracker. https://github.com/NRGI/resource-projects-dataload/issues/7
