### ISSUE TITLE
Duplicate values displayed

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#54]
[  ] Duplicate companies on Project page: http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/project/uy/afon-ud15wa.html

**Comment by timgdavies** [comment]
Using nested subqueries may be useful here to reduce the set of results.

For example, in the query below, as I understand (don't trust me entirely on this...), the subquery ```SELECT DISTINCT ?company``` is executed first, and then the label is captured. 

```sparql
prefix rp: <http://resourceprojects.org/def/>
prefix rp_misc: <http://resourceprojects.org/def/misc/>
prefix skos_: <http://www.w3.org/2004/02/skos/core#>

SELECT distinct str(?company_name) ?company WHERE {
  ?company skos_:prefLabel ?company_name
  { 
   SELECT DISTINCT ?company WHERE 
    {
      <PROJECT_URI> rp:hasStake ?stakes .
      ?stakes rp:hasStakeholder ?company .
      ?company a rp:Company . 
    }
  }
}
```

It is still possible here to get companies twice if they have different prefLabels - but that is something we should be cleaning in the source data.

**Comment by caprenter** [comment]
Thanks for this. I also saw this:
http://answers.semanticweb.com/questions/21137/how-to-prevent-duplicate-result-in-query-sparql-because-inference-add-many-triples

I think a useful step across many of the queries we have on place is going to be selecting only what we want (e.g. company, company_name) instead of '*', as well as the use of subqueries.

Good stuff. thanks

**Comment by caprenter** [comment]
I've been using this as a catch all for duplicates. I may close this and start separate issues for any more duplicates we see

**Comment by Bjwebb** [comment]
I think that probably makes sense.
