### ISSUE TITLE
Sort, order, placement of entities without names

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#55]
![uploads/c19b1253-545d-41c8-8e14-6e0bc8b81327/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc19b1253-545d-41c8-8e14-6e0bc8b81327%2Fblob)

**Comment by timgdavies** [comment]
Adding a filter to the query so then labels which are "" are considered to be blank seems to help here.

I.e. see the addition of ``` FILTER(str(?name)!="")``` to the query below within the optional block.

However, the other option here would be to just filter out anything without a label at all, as it's not clear we want to have projects without labels.

```sparql

PREFIX rp: <http://resourceprojects.org/def/>

SELECT DISTINCT * WHERE {
    ?uri a rp:Company
    OPTIONAL { ?uri skos:prefLabel ?name.
    FILTER(str(?name)!="") }

}
ORDER BY (?name)
limit 10000

```

This query will still display a project twice if it has more than one prefLabel. 

In future we will need to decide whether to deal with this by cleaning up the data, or handling it better in queries.

**Comment by caprenter** [comment]
This no longer seems to be an issue
