### ISSUE TITLE
Company Groupings

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#57]
Not sure how we can show these company groupings yet. i.e. the data is not there yet.

When it is, we will need new views for this, and each of our company lists will need to show the 'parent'

**Comment by anderspeders** [comment]
I believe that agreed to set up the architecture for this. 

We discussed: 
a) Reconciling corporate entities to OC
b) Leaning on the OC corporate grouping system, which I believe is essentially just establishing an affiliation. Also discussed here: https://github.com/NRGI/resourceprojects.org/issues/22
David also provided a rough list of corporate groupings based on major oil gas and mining companies.

I also think we have enough data to deal with this. 

For exmaple: 
<Corporate group> BP

<Corporate entities> which are already in the database: 
BP Amoco Refinery (Bulwer Island) Pty. Ltd.
BP Amoco Refinery (Kwinana) Pty. Ltd.
BP Aus. Holdings Ltd.(16.67%)
BP Berau Ltd.
BP Canada Inc. (The British Petroleum Co. plc, London: 100%)
BP East Kalimantan
BP Muturi Holdings BV
BP Muturi Ltd.
BP Petroleum Development of Norway
BP Raffinaderi AB
BP Trinidad and Tobago LLC
BP Trinidad and Tobago LLC
BP Trinidad and Tobago LLC (Operator)
BP Wiriagar Ltd.

cc @timgdavies

**Comment by timgdavies** [comment]
In #4c713675d5e5f436d07d6b7e496117acfe61be2b I've done some work towards this. Still needs group pages created.

**Comment by timgdavies** [comment]
This was delivered in the Alpha. 

The data load templates for Beta handle company groups.

Closing this issue - and opening a new one for group pages in the beta.
