### ISSUE TITLE
Downplay IDs in the design for when it goes online

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#59]
From conversation, we don't need to presenting ID's to people all the time!

See also:
https://github.com/NRGI/resourceprojects.org-frontend/issues/58

**Comment by caprenter** [comment]
This is done - unless you spot a bug

**Comment by anderspeders** [comment]
@caprenter I have an adjustment here: 

1) Collapse payment ID column
2) Move Payment year to the left
3) [not appearing in image] Change: *Type* --> *Payment type*

![corrections payment id](https://cloud.githubusercontent.com/assets/1101585/8861070/085a67d6-3156-11e5-9601-609237b82400.JPG)

**Comment by caprenter** [comment]
Moving columns and adding changing payment type are no problem.

Without the ID's I think it will be really hard to debug any problems, or enable people to discuss a particular payment. We could potentially do something like at a  'info' link somewhere (against each row of the table)
