### ISSUE TITLE
Adding/Editing data & user comments/interaction

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#60]
There is a desire to make it easy for people using the site to be able to suggest improvements to the data directly through the interface.

Editing data directly on the site is difficult at this stage.

Ways of doing this are still being explored. When this is agreed - calls to action sections need to be put into the application.

**Comment by anderspeders** [comment]
I see two use cases: 

As a user I would like to **flag** that the data is incorrect. 
As a user I would like to propose a correction

I agree that this is not a top priority. Right now getting proper flat file load templates is a much more important first step, as this will enable contributors with data skills to prepare data for the site.

**Comment by timgdavies** [comment]
Split out into issues #132 and #133
