### ISSUE TITLE
CSV output

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#68]
We should be providing csv output of each of our views

**Comment by Bjwebb** [comment]
I'm thinking the CSV that virtuoso produces from it's SPARQL endpoint is probably suitable for this. We need to get the compiled query from lodspeakr to construct the appropriate url. The most obvious way I can see of doing this involves a 1 line change to the lodspeakr source code - ie. creating our own fork. This would also allow us to fix https://github.com/NRGI/resourceprojects.org-frontend/issues/69

**Comment by timgdavies** [comment]
This sounds good to me. I think if we fork, and perhaps bundle up some things into a pull request in future, that makes sense.

**Comment by Bjwebb** [comment]
There are now two CSV links on http://lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/country/AO

The current CSV links have a hardcoded virtuoso URL that will want changing. We might want to just use `/sparql`, and ensure this is handled correctly by the reverse proxy everywhere we serve it.

I also assume we want to add more CSV links, one for each query that is pulled into the page?

**Comment by Bjwebb** [comment]
There are now concession type filters on http://lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/country/AO

@caprenter is this one for you to tidy up and take further, or do you want more input from me?

**Comment by Bjwebb** [comment]
CSV links, e.g. on http://lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/country/AO now link to /sparql , which means they'll now work correctly for the live site.

Remaining tasks, which I've split into separate issues:
* What should the CSV look like when we have pagination?
* Add CSV links for all queries https://github.com/NRGI/resourceprojects.org-frontend/issues/179
