### ISSUE TITLE
404 page is not styled unless it's at top level

### ISSUE THREAD

**Issue by Bjwebb** [NRGI/resourceprojects.org-frontend#77]
http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/a is styled.
http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/a/b is not.

**Comment by timgdavies** [comment]
Need to switch paths in header to start with /

**Comment by caprenter** [comment]
We're going to deal with this by setting all the dependency URLs in the header to / instead of {{lodspeakr.home}}

This means we may have to change it if we change the root of the application in future.
