### ISSUE TITLE
Top Navigation

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#86]
Top navigation should be:

About
Projects
Countries

We need to decide on Company Groups/Companies

My bid is to leave the navigation item as Companies, but to display company groups, and to show companies in that group on that page.

[Company Groups] will be a confusing navigation item because of the space in the name - will look like two options, and who knows what a company group is anyway!?

We will remove 'Licence' from the top menu

**Comment by timgdavies** [comment]
How about this:

Top nav: About | Projects | Countries | Companies

Within the Companies page have some sort of toggle between Companies (default) and Groups, perhaps using a button group at top of the page: http://getbootstrap.com/components/#btn-groups

**Comment by anderspeders** [comment]
Just seeing this now, 
Can we have the company group as the dominant?

Why: 
The main user will be interested to understand the projects of Tullow or Statoil - Statoil-17-Angola or Tullow-Ghana.

**Comment by timgdavies** [comment]
I would suggest we pick this up post-alpha through some design work with partners to understand how best to communicate both companies and groups, and to display the data best.

**Comment by caprenter** [comment]
I plan to implement the 'toggle between Companies (default) and Groups' suggested above this afternoon.
FYI  -groups are available at
http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/group
We just don't have a link to it yet

**Comment by anderspeders** [comment]
Thanks @caprenter, this is great!
