### ISSUE TITLE
typo on frontpage

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/resourceprojects.org-frontend#99]
![image](https://cloud.githubusercontent.com/assets/13120783/8854414/b0763fa2-3157-11e5-80b9-4242cb109615.png)

**Comment by davidmihalyi** [comment]
I meant add an S

**Comment by Bjwebb** [comment]
This should now be fixed - http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/index.html
